ignore-paths = [".venv"]

[container]
name             = "evalis"
image_name       = "evalis_silentshell_pi_env"
image_dockerfile = "./config/silentshell.Dockerfile"
image_user       = "mary"

[container.volumes]
"~/.claude"      = "/home/mary/.claude"
"~/.claude.json" = "/home/mary/.claude.json"
"~/.pi" = "/home/mary/.pi"

[env]
PYTHONDONTWRITEBYTECODE = "1"
